num1=int(input("enter first number"))
num2=int(input("enter second number"))
sum=num1+num2
difference=num1-num2
product=num1*num2
division=num1/num2
modulus=num1%num2
print(f"sum of {num1}+{num2}={sum}")
print(f"differnce of {num1}-{num2}={difference}")
print(f"product of {num1}*{num2}={product}")
print(f"division of {num1}/{num2}={division}")
print(f"modulus of {num1}%{num2}={modulus}")
